<a href="https://colab.research.google.com/github/AnshumanMohapatra11121999/DataScienceAndAI-/blob/main/NUMPY_REVISION_part_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#INSTALL NUMPY
!pip install numpy

In [ ]:
import numpy as np

In [ ]:
arr1d=np.array([1,2,3,4,5,6])

In [ ]:
arr1d#Original array

array([1, 2, 3, 4, 5, 6])

In [ ]:
#Access 1 element
print(arr1d[-1])

6


In [ ]:
#1d to 2d and vice versa conversion of numpy array

In [ ]:
arr2d=arr1d.reshape(2,3)

In [ ]:
arr2d.shape

(2, 3)

In [ ]:
arr2d

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
#We canreshape any dimension array to 1 dimension using -1 in the reshape() function and keeping its order intact
arr2dreshaped_to_1d=arr2d.reshape(-1)
print("The original array",arr2d)
print("The one d array it made",arr2dreshaped_to_1d)

The original array [[1 2 3]
 [4 5 6]]
The one d array it made [1 2 3 4 5 6]


In [ ]:
#arange function
arran=np.arange(1,10,2)

In [ ]:
print(arran)

[1 3 5 7 9]


In [ ]:

array1=np.array([0,0,0,0,0,0,0,0,0,0]).reshape(2,5)
array2=np.array([1,1,1,1,1,1,1,1,1,1]).reshape(2,5)
#Horizontal stacking
hzstack=np.hstack([array1,array2])
print(hzstack)
#Vertical stacking
vtstack=np.vstack([array1,array2])
print(vtstack)

[[0 0 0 0 0 1 1 1 1 1]
 [0 0 0 0 0 1 1 1 1 1]]
[[0 0 0 0 0]
 [0 0 0 0 0]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [ ]:
#Lets get the inverse of a matrix using numpy
#A 2d array is known as matrix in numpy for example
a=np.array([[1,2],
           [3,4]])
#A is a matrix here
#Inorder to find the inverse of an matrix the formulae is inverse of matrix a =determinant of a *adjoint of a
#Lets find the inverse of matrix a in the python using numpy
a_inver=np.linalg.inv(a)
print("\n The origional matrix")
print(a)
print("The inverse of 'a' the origional matrix\n",a_inver)


 The origional matrix
[[1 2]
 [3 4]]
The inverse of 'a' the origional matrix
 [[-2.   1. ]
 [ 1.5 -0.5]]


In [ ]:
#Vectorized:Vectorization in NumPy is the idea of performing operations on entire arrays at once instead of looping over individual elements in Python.
#Lets take an example of an function f(x)=x^2+2x+1
def my_func(x):
  return x**2+2*x+1

In [ ]:
#Create an array
arr=np.array([1,2,3,4,5])
#For different value present in x I want to use all these values in the function "my_func"
#Lets do it using vectorized
result=np.vectorize(my_func)(arr)
print(result)

[ 4  9 16 25 36]


In [ ]:
import numpy as np

# -------------------------------
# Shallow Copy vs Deep Copy in NumPy
# -------------------------------

m = np.array([1, 2, 3, 4, 5])
# Original NumPy array created

n = m
# n is NOT a new array
# n is just another reference to the same memory as m
# This behaves like a SHALLOW COPY (reference assignment)

o = np.copy(m)
# o is a DEEP COPY
# A new array with a new memory location is created
# Changes in m will NOT affect o

print("Before changes:")
print("m:", m)
print("n:", n)
print("o:", o)

# -------------------------------
# Modifying original array
# -------------------------------

m[0] = 9
# Changing first element of m

print("\nAfter changing m[0] = 9:")
print("m:", m)
# m reflects the change

print("n:", n)
# n ALSO reflects the change because it shares memory with m

print("o:", o)
# o does NOT change because it has separate memory


Before changes:
m: [1 2 3 4 5]
n: [1 2 3 4 5]
o: [1 2 3 4 5]

After changing m[0] = 9:
m: [9 2 3 4 5]
n: [9 2 3 4 5]
o: [1 2 3 4 5]


In [ ]:
#some convenient method of np array
import numpy as np
a=np.zeros((2,2))#Create array of 0s
b=np.ones((2,2))#create array of 1s
c=np.random.rand(2,3)#create array of random numbers
d=np.random.randint(2,100,size=5)#Create array of random integers with space of 5 between each and then selects
e=np.eye(3)#Create identity matrix where diagonel elements have 3 1s
print(a)
print(b)
print(c)
print(d)
print(e)



[[0. 0.]
 [0. 0.]]
[[1. 1.]
 [1. 1.]]
[[0.35115628 0.69798512 0.70308356]
 [0.528753   0.67461712 0.60914   ]]
[45 77 36 32 49]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
# =========================
# NUMPY COMPLETE CHEAT SHEET
# (1D & 2D ARRAYS)
# SINGLE CELL WITH PRINTS
# =========================

import numpy as np

print("----- Creating 1D Array -----")
a = np.array([1, 2, 3, 4, 5])
print(a)
# 1D NumPy array created


print("\n----- Creating 2D Array -----")
b = np.array([[1, 2, 3],
              [4, 5, 6]])
print(b)
# 2D NumPy array created


print("\n----- Array Attributes -----")
print("a ndim:", a.ndim)
print("b ndim:", b.ndim)
print("a shape:", a.shape)
print("b shape:", b.shape)
print("a size:", a.size)
print("b size:", b.size)
print("a dtype:", a.dtype)
# Basic properties of arrays


print("\n----- Special Arrays -----")
z = np.zeros((2, 3))
print("Zeros:\n", z)

o = np.ones((2, 2))
print("Ones:\n", o)

i = np.eye(3)
print("Identity Matrix:\n", i)
# Zeros, ones, and identity matrix


print("\n----- Range Based Arrays -----")
r = np.arange(1, 10, 2)
print("Arange:", r)

l = np.linspace(0, 1, 5)
print("Linspace:", l)
# Creating arrays using range and spacing


print("\n----- Reshape vs Resize -----")
c = np.array([1, 2, 3, 4, 5, 6])
print("Original array c:", c)

reshaped_c = c.reshape(2, 3)
print("After reshape (2x3):\n", reshaped_c)
print("Original c after reshape:", c)
# reshape() DOES NOT change original array


d = np.array([1, 2, 3, 4, 5, 6])
print("\nOriginal array d:", d)

d.resize(2, 3)
print("After resize (2x3):\n", d)
# resize() CHANGES original array


e = np.array([1, 2, 3])
print("\nOriginal array e:", e)

e.resize(2, 3)
print("After resize (size increased):\n", e)
# resize() repeats elements if size increases


print("\n----- Flatten -----")
b_flat = b.flatten()
print("Flattened b:", b_flat)
# Converts 2D array to 1D


print("\n----- Indexing & Slicing -----")
print("First element of a:", a[0])
print("Last element of a:", a[-1])
print("Slice a[1:4]:", a[1:4])
print("Element at row 0 col 1 in b:", b[0, 1])
print("Second column of b:", b[:, 1])
# Accessing and slicing arrays


print("\n----- Vectorized Operations -----")
print("a + 10:", a + 10)
print("a * 2:", a * 2)
print("a squared:", a ** 2)
# Element-wise operations without loops


print("\n----- Universal Functions -----")
print("Square root:", np.sqrt(a))
print("Sum:", np.sum(a))
print("Mean:", np.mean(a))
print("Max:", np.max(a))
print("Min:", np.min(a))
print("Std Dev:", np.std(a))
# Mathematical and statistical functions


print("\n----- Axis Operations -----")
print("Column-wise sum of b:", np.sum(b, axis=0))
print("Row-wise sum of b:", np.sum(b, axis=1))
# Axis-based operations in 2D arrays


print("\n----- Boolean Indexing -----")
print("a > 3:", a > 3)
print("Filtered values:", a[a > 3])
# Filtering using conditions


print("\n----- Random Arrays -----")
np.random.seed(42)
rand1 = np.random.rand(5)
print("Random 1D:", rand1)

rand2 = np.random.randint(1, 10, size=(2, 3))
print("Random 2D:\n", rand2)
# Random number generation


print("\n----- Sorting & Searching -----")
print("Sorted a:", np.sort(a))
print("Index of max:", np.argmax(a))
print("Index of min:", np.argmin(a))
# Sorting and searching operations


print("\n----- Matrix Operations -----")
x = np.array([[1, 2],
              [3, 4]])
y = np.array([[5, 6],
              [7, 8]])

print("Matrix x:\n", x)
print("Matrix y:\n", y)
print("Addition:\n", x + y)
print("Multiplication:\n", x @ y)
print("Transpose:\n", x.T)
print("Determinant:", np.linalg.det(x))
print("Inverse:\n", np.linalg.inv(x))
# Linear algebra operations


print("\n----- Copy vs View -----")
v = a.view()
v[0] = 100
print("View:", v)
print("Original a after view:", a)
# View affects original array

a = np.array([1, 2, 3, 4, 5])  # reset
cp = a.copy()
cp[0] = 200
print("Copy:", cp)
print("Original a after copy:", a)
# Copy does NOT affect original array


----- Creating 1D Array -----
[1 2 3 4 5]

----- Creating 2D Array -----
[[1 2 3]
 [4 5 6]]

----- Array Attributes -----
a ndim: 1
b ndim: 2
a shape: (5,)
b shape: (2, 3)
a size: 5
b size: 6
a dtype: int64

----- Special Arrays -----
Zeros:
 [[0. 0. 0.]
 [0. 0. 0.]]
Ones:
 [[1. 1.]
 [1. 1.]]
Identity Matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

----- Range Based Arrays -----
Arange: [1 3 5 7 9]
Linspace: [0.   0.25 0.5  0.75 1.  ]

----- Reshape vs Resize -----
Original array c: [1 2 3 4 5 6]
After reshape (2x3):
 [[1 2 3]
 [4 5 6]]
Original c after reshape: [1 2 3 4 5 6]

Original array d: [1 2 3 4 5 6]
After resize (2x3):
 [[1 2 3]
 [4 5 6]]

Original array e: [1 2 3]
After resize (size increased):
 [[1 2 3]
 [0 0 0]]

----- Flatten -----
Flattened b: [1 2 3 4 5 6]

----- Indexing & Slicing -----
First element of a: 1
Last element of a: 5
Slice a[1:4]: [2 3 4]
Element at row 0 col 1 in b: 2
Second column of b: [2 5]

----- Vectorized Operations -----
a + 10: [11 12 13 14 15]
a * 2

In [ ]:
#I have made changes and updated in the same ipynb file in the repo....